# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_name', models.CharField(max_length=200)),
                ('bus_license_plate', models.CharField(max_length=20)),
                ('Depart_Date', models.DateField(max_length=10)),
                ('Depart_Time', models.CharField(max_length=10)),
                ('Depart_Location', models.DateField(max_length=50)),
                ('Arrival_Date', models.DateField(max_length=10)),
                ('Arrival_Time', models.CharField(max_length=10)),
                ('Arrival_Location', models.CharField(max_length=50)),
                ('Total_Seats', models.IntegerField(max_length=100)),
                ('Ticket_cost', models.IntegerField(max_length=100)),
            ],
        ),
    ]
