# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20170712_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustimetable',
            name='Depart_Location',
            field=models.CharField(max_length=50),
        ),
    ]
