# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_auto_20170713_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustimetable',
            name='Ticket_cost',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='bustimetable',
            name='Total_Seats',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
